### PR TITLE
Remove the extensionPath config key

### PR DESCRIPTION
**Pull request by eduardomezencio**
This pull request addresses two things, actually:

1. Removal of extensionPath from the configs.
2. Exclusion of generated files from the repository and addition to .gitignore. Files affected: *.js, *.map, and lldebugger.lua. These files should be generated during the build process and not included in version control.

Details:

1. Removal of extensionPath:
The extensionPath config key was initially used to add the extension path to the Lua path before executing user code so that it could locate lldebugger.lua when required. The code has been updated to use `__dirname` to find the path, eliminating the need for this configuration key. This change simplifies the server configuration for Vim/Neovim or any other non-vscode editor while maintaining compatibility with vscode. The functionality has been tested by and confirmed to work in vscode. I have tested only in Linux, though.

2. Exclusion of generated files:
The generated files (*.js, *.map, and lldebugger.lua) have been removed from the repository and added to .gitignore. This cleanup makes the codebase easier to work with, as files generated during the build should not be part of version control.

Testing
Linux: Changes have been tested and verified on neovim and vscode.
Windows and macOS: Need someone to thest on these

### CODE REVIEW

**Comment by sewbacca** [comment]
Shoudln't this be two different PRs then? One for cleaning up the repo and one for removing the extensionPath config key?

**Comment by eduardomezencio** [comment]
I sadly agree with you, I didn't want to open two, partially for laziness. The thing is that I didn't intend to do the cleaning, but while navigating and editing the code I couldn't not do it, because it was bothering me. I can separate them, if you guys think I should.

**Comment by sewbacca** [comment]
The cleanup was something I wanted to do anyway, which I believe could be merged faster. The removal of the extensionPath config key would be something I'd have to take a closer look. The -3420 changes made my eyes pop a bit.

**Comment by eduardomezencio** [comment]
I'll actually separate them, I think it's better. Give me some minutes

**Comment by eduardomezencio** [comment]
https://github.com/Ismoh/local-lua-debugger-vscode/pull/16

This is only the cleanup, after merging, this one here will be a lot simpler, dealing only with removing the config and making the debugger work without it

**Comment by eduardomezencio** [comment]
Now I also have also this other pull request: https://github.com/Ismoh/local-lua-debugger-vscode/pull/17

So I have closed this one

**Pull request closed without merging**
