### PR TITLE
[Snyk] Upgrade @vscode/debugadapter from 1.64.0 to 1.65.0

### PR DESCRIPTION
**Pull request by Ismoh**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade @vscode/debugadapter from 1.64.0 to 1.65.0.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **1 version** ahead of your current version.
- The recommended version was released **22 days ago**, on 2024-02-27.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>@vscode/debugadapter</b></summary>
    <ul>
      <li>
        <b>1.65.0</b> - <a href="https://snyk.io/redirect/github/microsoft/vscode-debugadapter-node/releases/tag/v1.65.0">2024-02-27</a></br><p>v1.65.0</p>
      </li>
      <li>
        <b>1.64.0</b> - <a href="https://snyk.io/redirect/github/microsoft/vscode-debugadapter-node/releases/tag/v1.64.0">2023-10-27</a></br><p>v1.64.0</p>
      </li>
    </ul>
    from <a href="https://snyk.io/redirect/github/microsoft/vscode-debugadapter-node/releases">@vscode/debugadapter GitHub release notes</a>
  </details>
</details>
<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/ismoh/project/3471efa2-c570-43e7-9f4f-e160c298de38?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/ismoh/project/3471efa2-c570-43e7-9f4f-e160c298de38/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/ismoh/project/3471efa2-c570-43e7-9f4f-e160c298de38/settings/integration?pkg&#x3D;@vscode/debugadapter&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Comment by Ismoh** [comment]
Needs to be tested locally. Feel free to run npm commands locally to see, if the newer version works fine.

**Comment by sewbacca** [comment]
It feels weird, that a bot created this PR with your account. Wouldn't it make more sense, if the bot itself would open the PR?

I've tested this superficially and it looks alright.

**Comment by Ismoh** [comment]
Yea, it's weird. Didn't change any snyk config yet. This might help, although this is a public repo:
https://support.snyk.io/hc/en-us/articles/360004931097-Why-do-all-the-Github-Pull-Requests-show-me-as-the-creator-and-not-snyk-bot

**Comment by Ismoh** [comment]
In addition it would be awesome to add some pr/merge checks in future.

**Comment by Ismoh** [comment]
I would merge this before #12 and #13. What do you think @sewbacca ?

**Comment by sewbacca** [comment]
Agreed, I'll adjust it in the git history and then create a release. Is that alright?

**Comment by sewbacca** [comment]
I skipped rebasing, since I believe that would mess up the verifications for the commits.

**Comment by Ismoh** [comment]
> I skipped rebasing, since I believe that would mess up the verifications for the commits.

Why messed up? Looks fine to me. I'll take a look into it today.

**Pull request merged**
